### ISSUE TITLE
Fails to render BarChart

### ISSUE THREAD

**Issue by adel121** [EvHaus/react-pdf-charts#416]
### Describe the bug

Currently, when trying to embed a Barchart, it fails with the following error:

```
[react-pdf-charts]: Your chart rendered a <p /> node which isn't supported by <ReactPDFChart /> yet. Please report this issue.
    at Object.replaceHtmlWithPdfSvg [as replace] (http://localhost:3000/static/js/bundle.js:340521:13)
    at domToReact (http://localhost:3000/static/js/bundle.js:130001:36)
    at Object.replaceHtmlWithPdfSvg [as replace] (http://localhost:3000/static/js/bundle.js:340345:86)
    at domToReact (http://localhost:3000/static/js/bundle.js:130001:36)
    at Object.replaceHtmlWithPdfSvg [as replace] (http://localhost:3000/static/js/bundle.js:340345:86)
    at domToReact (http://localhost:3000/static/js/bundle.js:130001:36)
    at Object.replaceHtmlWithPdfSvg [as replace] (http://localhost:3000/static/js/bundle.js:340345:86)
    at domToReact (http://localhost:3000/static/js/bundle.js:130001:36)
    at HTMLReactParser (http://localhost:3000/static/js/bundle.js:130154:37)
    at webSvgToPdfSvg (http://localhost:3000/static/js/bundle.js:340525:71)
```

### Reproduction

You can reproduce with the same code from the recharts docs.

```
const SomeComponent = () => (
    <ReactPDFChart>
        <BarChart width={730} height={250} data={data}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="name" />
            <YAxis />
            <Tooltip />
            <Legend />
            <Bar dataKey="pv" fill="#8884d8" />
            <Bar dataKey="uv" fill="#82ca9d" />
        </BarChart>

    </ReactPDFChart>
);
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/EvHaus/react-pdf-charts/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that you're confident that this is a legitimate bug. To ask a question open a [GitHub Discussion](https://github.com/EvHaus/react-pdf-charts/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by EvHaus** [comment]
You'll need to remove the `<Tooltip />` component. PDFs don't support tooltips.
